### PR TITLE
[WIP] refactoring for new mongo php driver

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
depends on: https://github.com/mongodb/mongo-php-driver/issues/133 and https://github.com/mongodb/mongo-php-driver/issues/132

**Comment by prolic** [comment]
will resolve https://github.com/prooph/event-store-mongodb-adapter/issues/41

**Comment by prolic** [comment]
stashed commits

**Comment by sandrokeil** [comment]
@prolic What is the status? The MongoDB extension has version 1.1.2 now. The prooph Docker images has the MongoDB extension installed.

**Comment by prolic** [comment]
To be more specifc: I am waiting for mongo-php-library 1.1, especially this PR: https://github.com/mongodb/mongo-php-library/pull/57

**Comment by bweston92** [comment]
@prolic that PR on mongo-php-library is closed, is this going to effect anything?

**Comment by prolic** [comment]
This will be finished with new major release for PHP 7.1

**Pull request closed without merging**
